# Generated by Django 4.2.16 on 2025-02-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AListAccount',
            fields=[
                ('channel_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'AList Accounts',
            },
        ),
        migrations.CreateModel(
            name='BilibiliAccount',
            fields=[
                ('channel_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sess', models.CharField(max_length=500)),
                ('bili_jct', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Bilibili Accounts',
            },
        ),
        migrations.CreateModel(
            name='CallingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agora_key', models.CharField(max_length=100)),
                ('agora_certification', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Calling Configuration',
            },
        ),
        migrations.CreateModel(
            name='ChatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tencent_admin_name', models.CharField(max_length=100)),
                ('tencent_app_id', models.CharField(max_length=100)),
                ('tencent_app_key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Chat Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Bunga Server', max_length=100)),
                ('allow_new_client', models.BooleanField(default=True)),
                ('alist_host', models.URLField()),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
