# Generated by Django 5.1.6 on 2025-11-18 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alisthost_remove_site_alist_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alistaccount',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alistaccount',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bilibiliaccount',
            name='bili_jct',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bilibiliaccount',
            name='refresh_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bilibiliaccount',
            name='sess',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.channel')),
            ],
            options={
                'unique_together': {('channel', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='subtitles/')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='server.videorecord')),
            ],
        ),
    ]
