# Generated by Django 5.1.6 on 2025-11-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_alistaccount_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='name',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
