# Generated by Django 5.1.6 on 2025-11-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_subtitle_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='server.videorecord'),
        ),
    ]
