# Generated by Django 5.1.6 on 2025-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_subtitle_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
