# Generated by Django 5.1.6 on 2025-11-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_videorecord_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videorecord',
            name='source',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videorecord',
            name='thumbUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
