# Generated by Django 5.1.6 on 2025-11-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_videorecord_path_videorecord_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorecord',
            name='position',
        ),
        migrations.CreateModel(
            name='PlayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('video_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_status', to='server.videorecord')),
            ],
        ),
    ]
