# Generated by Django 5.1.6 on 2025-11-20 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_remove_videorecord_position_playstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playstatus',
            name='position',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
