# Generated by Django 5.1.6 on 2025-11-22 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_playstatus_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='position',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.DeleteModel(
            name='PlayStatus',
        ),
    ]
