# Generated by Django 5.1.6 on 2025-11-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_videorecord_position_delete_playstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videorecord',
            old_name='thumbUrl',
            new_name='thumb_url',
        ),
    ]
