# Generated by Django 5.1.6 on 2025-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_rename_thumburl_videorecord_thumb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecord',
            name='thumb_url',
            field=models.URLField(null=True),
        ),
    ]
