# Generated by Django 5.1.6 on 2025-11-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_videorecord_thumb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecord',
            name='thumb_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
