# Generated by Django 6.0.2 on 2026-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_videorecord_options_clientlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='noname', max_length=200),
            preserve_default=False,
        ),
    ]
