# Generated by Django 6.0.2 on 2026-03-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linker_id', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
